import { defineConfig, globalIgnores, type Config } from 'eslint/config';
import tsImports from 'eslint-config-vaadin/imports-typescript';
import prettier from 'eslint-config-vaadin/prettier';
import testing from 'eslint-config-vaadin/testing';
import tsRequireTypeChecking from 'eslint-config-vaadin/typescript-requiring-type-checking';
import oxlint from 'eslint-plugin-oxlint';

const config: readonly Config[] = defineConfig(
  globalIgnores([
    '.nx/**/*',
    '.vite/**/*',
    '.vite-inspect/**/*',
    '.docs/**/*',
    '.storybook-static/**/*',
    'button/**/*',
    'button-group/**/*',
    'checkbox/**/*',
    'core/**/*',
    'fab/**/*',
    'icon/**/*',
    'radio/**/*',
    'text-field/**/*',
    'attribute.js',
    'attribute.js.map',
    'attribute.d.ts',
    'attribute.d.ts.map',
    'controllers/**/*',
    'element.js',
    'element.js.map',
    'element.d.ts',
    'element.d.ts.map',
    'emitter.js',
    'emitter.js.map',
    'emitter.d.ts',
    'emitter.d.ts.map',
    'traits/**/*',
    'utils/**/*',
    '_virtual/**/*',
    'custom-elements.json',
    'react.d.ts',
    'react.d.ts.map',
    'packages/*/dist/**/*',
    'packages/*/custom-elements.json',
    'packages/material-x/button/**/*',
    'packages/material-x/button-group/**/*',
    'packages/material-x/checkbox/**/*',
    'packages/material-x/fab/**/*',
    'packages/material-x/icon/**/*',
    'packages/material-x/radio/**/*',
    'packages/material-x/text-field/**/*',
    'packages/material-x/core/**/*',
    'packages/material-x/react.d.ts',
    'packages/material-x/react.d.ts.map',
    'packages/core/attribute.js',
    'packages/core/attribute.js.map',
    'packages/core/attribute.d.ts',
    'packages/core/attribute.d.ts.map',
    'packages/core/controllers/**/*',
    'packages/core/element.js',
    'packages/core/element.js.map',
    'packages/core/element.d.ts',
    'packages/core/element.d.ts.map',
    'packages/core/emitter.js',
    'packages/core/emitter.js.map',
    'packages/core/emitter.d.ts',
    'packages/core/emitter.d.ts.map',
    'packages/core/traits/**/*',
    'packages/core/utils/**/*',
    'packages/core/_virtual/**/*',
    'packages/material-x/**/*.js',
    'packages/material-x/**/*.js.map',
    'packages/material-x/**/*.d.ts',
    'packages/material-x/**/*.d.ts.map',
    'packages/core/**/*.js',
    'packages/core/**/*.js.map',
    'packages/core/**/*.d.ts',
    'packages/core/**/*.d.ts.map',
    'packages/tproc/**/*.js',
    'packages/tproc/**/*.js.map',
    'packages/tproc/**/*.d.ts',
    'packages/tproc/**/*.d.ts.map',
    'packages/vite-traits-plugin/index.js',
    'packages/vite-traits-plugin/index.js.map',
    'packages/vite-traits-plugin/index.d.ts',
    'packages/vite-traits-plugin/src/__fixtures__/**/*',
  ]),
  ...tsRequireTypeChecking,
  ...tsImports,
  ...testing,
  ...prettier,
  {
    files: ['**/*.{ts,tsx,mts,cts}'],
    rules: {
      '@typescript-eslint/no-use-before-define': 'off',
      '@typescript-eslint/no-shadow': 'off',
      '@typescript-eslint/unbound-method': 'off',
      'import-x/no-unresolved': [
        'error',
        {
          ignore: ['\\.css$', '\\.html$'],
        },
      ],
      'import-x/no-unassigned-import': 'off',
      'import-x/no-duplicates': 'off',
      'import-x/no-extraneous-dependencies': 'off',
      'import-x/prefer-default-export': 'off',
    },
  },
  ...oxlint.buildFromOxlintConfigFile('./.oxlintrc.json'),
  {
    // disable rules duplicated in Oxlint but not handled by
    // `buildFromOxlintConfigFile`.
    rules: {
      '@typescript-eslint/no-unsafe-type-assertion': 'off',
      'import-x/no-mutable-exports': 'off',
      '@typescript-eslint/promise-function-async': 'off',
    },
  },
);

export default config;
