import { defineConfig, type UserConfig } from 'tsdown';
import {
  constructLibraryTsdownPlugins,
  createPackageCustomExports,
  type PackageExportsMap,
} from '../../tsdown.config.ts';

const ENTRYPOINTS = [
  'attribute',
  'controllers',
  'controllers/useARIA',
  'controllers/useAttributes',
  'controllers/useConnected',
  'controllers/useContext',
  'controllers/useEvents',
  'controllers/useKeyboard',
  'controllers/useMutationObserver',
  'controllers/useResizeObserver',
  'controllers/useRovingTabindex',
  'controllers/useShadowDOM',
  'controllers/useSlot',
  'elements',
  'emitter',
  'reactive-controller',
  'reactive-element',
  'traits-entry',
  'traits',
  'traits/checkable',
  'traits/disableable',
  'traits/valuable',
  'utils',
  'utils/CSSVariableError',
  'utils/DOM',
  'utils/readCSSVariables',
  'utils/runtime',
] as const;

const EXPORTS: PackageExportsMap = {
  './attribute': 'attribute',
  './controllers': 'controllers',
  './controllers/useARIA': 'controllers/useARIA',
  './controllers/useAttributes': 'controllers/useAttributes',
  './controllers/useConnected': 'controllers/useConnected',
  './controllers/useContext': 'controllers/useContext',
  './controllers/useEvents': 'controllers/useEvents',
  './controllers/useKeyboard': 'controllers/useKeyboard',
  './controllers/useMutationObserver': 'controllers/useMutationObserver',
  './controllers/useResizeObserver': 'controllers/useResizeObserver',
  './controllers/useRovingTabindex': 'controllers/useRovingTabindex',
  './controllers/useShadowDOM': 'controllers/useShadowDOM',
  './controllers/useSlot': 'controllers/useSlot',
  './elements': 'elements',
  './emitter': 'emitter',
  './reactive-controller': 'reactive-controller',
  './reactive-element': 'reactive-element',
  './traits': 'traits-entry',
  './traits/checkable': 'traits/checkable',
  './traits/disableable': 'traits/disableable',
  './traits/valuable': 'traits/valuable',
  './utils': 'utils',
  './utils/CSSVariableError': 'utils/CSSVariableError',
  './utils/DOM': 'utils/DOM',
  './utils/readCSSVariables': 'utils/readCSSVariables',
  './utils/runtime': 'utils/runtime',
  './package.json': './package.json',
};

const config: UserConfig = defineConfig({
  entry: ENTRYPOINTS.map((entrypoint) => `src/${entrypoint}.ts`),
  platform: 'neutral',
  exports: createPackageCustomExports(EXPORTS),
  dts: true,
  format: 'esm',
  sourcemap: true,
  target: 'esnext',
  outDir: '.',
  fixedExtension: false,
  clean: false,
  plugins: constructLibraryTsdownPlugins(),
  unbundle: true,
});

export default config;
