// The `typescript` dependency is aliased to the `@typescript/typescript6`
// wrapper (TS 6, kept for tooling that isn't yet compatible with tsgo / TS 7).
// That wrapper re-exports `lib/tsc.js`, `lib/typescript.js`, etc. but NOT
// `lib/tsserver.js`, so `typescript-language-server` — which resolves its
// engine via `node_modules/typescript/lib/tsserver.js` — fails to start.
//
// The real TS 6 tsserver lives in the wrapper's `@typescript/old` dependency.
// We drop the missing forwarding entrypoint into the wrapper's `lib/`, using
// the exact same idiom as its sibling stubs. The wrapper package is CommonJS,
// so the entrypoint must use `require` (Node spawns it inside that CJS
// package). Requiring the real entry keeps its own `__dirname`, so tsserver
// still resolves `lib.d.ts`, `typingsInstaller.js`, etc. from `@typescript/old`.

import { writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

async function main(): Promise<void> {
  let wrapperRoot: string;
  try {
    // Resolving both packages doubles as the "deps installed?" guard, so the
    // postinstall hook stays silent (never breaks an install) before `npm i`.
    import.meta.resolve('@typescript/old/lib/tsserver.js');
    wrapperRoot = dirname(
      fileURLToPath(import.meta.resolve('typescript/package.json')),
    );
  } catch {
    return;
  }

  await writeFile(
    join(wrapperRoot, 'lib', 'tsserver.js'),
    "// Generated by .scripts/link-tsserver.ts — forwards to the real TS 6 tsserver.\nrequire('@typescript/old/lib/tsserver.js');\n",
  );
}

await main();
