/**
 * Authoritative draggable machine entrypoint. Protocol algebra and lifecycle
 * decisions are decomposed under `./machine/`; consumers import them here.
 */

export {
  DRAG_ACQUIRING,
  DRAG_AWAITING_CONSUMER,
  DRAG_FINALIZING,
  DRAG_IDLE,
  DRAG_PENDING,
  DRAG_PENDING_ARMING,
  DRAG_REPORTING_FAILURE,
  DRAG_RESOLVING_RELEASE,
  DRAG_SETTLING,
  DRAG_STARTING,
  DRAGGING,
  type ActivationCandidate,
  type ActiveOperation,
  type DraggableLifecycle,
  type DraggablePolicy,
  type DraggableState,
  type LandingCurrency,
  type MotionCurrency,
  type ResolutionCurrency,
} from './machine/state.ts';

export {
  ACTIVATION_FAILED,
  ACTIVATION_READY,
  ADMIT_POINTER,
  CONTROLLED_POSITION,
  CONTROLLED_POSITION_FAILED,
  CONTROLLED_POSITION_RESOLVED,
  DROP_RESOLUTION_FAILED,
  DROP_RESOLVED,
  FAILURE_REPORTED,
  FINALIZATION_COMPLETED,
  FINALIZATION_FAILED,
  INTERACTION_STOPPED,
  INVALIDATED,
  LANDING_FAILED,
  LANDING_FINISHED,
  LANDING_PIN_FAILED,
  LANDING_PINNED,
  LANDING_PLAN_FAILED,
  LANDING_PLAN_RESOLVED,
  LANDING_START_FAILED,
  LANDING_STARTED,
  MOTION_OBSERVATION_FAILED,
  MOTION_OBSERVED,
  MOTION_PRESENTATION_FAILED,
  MOVE_CALLBACK_FAILED,
  MOVE_CALLBACK_SUCCEEDED,
  OPERATION_ARM_FAILED,
  OPERATION_ARMED,
  OPERATION_CANCELED,
  POINTER_MOVED,
  POINTER_RELEASED,
  POLICY_UPDATED,
  PRESENTATION_SETTLED,
  RELEASE_FAILED,
  RELEASE_RESOLVED,
  START_FAILED,
  START_SUCCEEDED,
  type ActivationFailedDraggableEvent,
  type ActivationReadyDraggableEvent,
  type AdmitPointerDraggableEvent,
  type ControlledPositionDraggableEvent,
  type ControlledPositionFailedDraggableEvent,
  type ControlledPositionResolvedDraggableEvent,
  type DraggableEvent,
  type DropResolutionFailedDraggableEvent,
  type DropResolvedDraggableEvent,
  type FailureReportedDraggableEvent,
  type FinalizationCompletedDraggableEvent,
  type FinalizationFailedDraggableEvent,
  type InteractionStoppedDraggableEvent,
  type InvalidatedDraggableEvent,
  type LandingFailedDraggableEvent,
  type LandingFinishedDraggableEvent,
  type LandingPinFailedDraggableEvent,
  type LandingPinnedDraggableEvent,
  type LandingPlanFailedDraggableEvent,
  type LandingPlanResolvedDraggableEvent,
  type LandingStartFailedDraggableEvent,
  type LandingStartedDraggableEvent,
  type MotionObservationFailedDraggableEvent,
  type MotionObservedDraggableEvent,
  type MotionPresentationFailedDraggableEvent,
  type MoveCallbackFailedDraggableEvent,
  type MoveCallbackSucceededDraggableEvent,
  type OperationArmFailedDraggableEvent,
  type OperationArmedDraggableEvent,
  type OperationCanceledDraggableEvent,
  type PointerMovedDraggableEvent,
  type PointerReleasedDraggableEvent,
  type PolicyUpdatedDraggableEvent,
  type PresentationSettledDraggableEvent,
  type ReleaseFailedDraggableEvent,
  type ReleaseResolvedDraggableEvent,
  type StartFailedDraggableEvent,
  type StartSucceededDraggableEvent,
} from './machine/event.ts';

export {
  ACQUIRE_FREE_ACTIVATION,
  BEGIN_POINTER_OPERATION,
  DISARM_OPERATION,
  FINALIZE_OPERATION,
  INVOKE_MOVE,
  INVOKE_START,
  OBSERVE_CONTROLLED_POSITION,
  OBSERVE_FREE_MOTION,
  OPEN_DROP_RESOLUTION,
  PIN_LANDING,
  PREPARE_FREE_LANDING,
  PRESENT_MOTION,
  REPORT_FAILURE,
  RESOLVE_FREE_RELEASE,
  RETIRE_OPERATION,
  START_LANDING,
  STOP_INTERACTION,
  WATCH_PRESENTATION,
  type DraggableDecision,
  type DraggableEffect,
  type DraggableEffectDeps,
  type DraggableMachineConfig,
  type GeometryRequest,
} from './machine/effect.ts';

export {
  createDraggableMachine,
  createInitialDraggableState,
} from './machine/decide.ts';
